language: cpp
sudo: false
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
  - os: osx
    osx_image: xcode9
    compiler: clang
    env: COMPILER=clang++
  - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER=clang++
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['clang-6.0', 'g++-7']
    env: COMPILER=clang++-6.0
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ["ubuntu-toolchain-r-test"]
        packages: ["g++-7"]
    env: COMPILER=g++-7
  - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-6"]
      env: COMPILER=g++-6

before_install:
- export CXX=${COMPILER}

script:
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
