version: 1.0.{build}

image: Visual Studio 2015

environment:
  BUILD_DIR: "%APPVEYOR_BUILD_FOLDER%\\build"

platform:
  - Win32

configuration:
  - Release

before_build:
  - cd %BUILD_DIR%
  - cmake .. -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 14 2015"

build:
  parallel: true
  verbosity: minimal
